baseURL = "https://zerodemy.com"
title = "Zerodemy Books"

languageCode = "bn-BD"
DefaultContentLanguage = "en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

paginate = 10

# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
ordersectionsby = "weight" # ordersectionsby = "title"
disableSearch = false # default is false
disableReadmoreNav = false # set true to hide prev/next navigation, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = true # set true to open shortcuts links to a new tab/window
subtitle = "Collection of Bengali Books"
siteURL = "https://zerodemy.com"
title_bn = "জিরোডেমি বই"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
home = [ "HTML", "RSS", "JSON"]
