baseURL = "https://zerodemy.com"
title = "Zerodemy Books"
languageCode = "bn-BD"
DefaultContentLanguage = "bn"
defaultContentLanguage = "bn"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false
paginate = 10

# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
siteSubTitle = "Collection of Bengali Books"
siteSubTitleBN = "বাংলা বইয়ের সংগ্রহশালা"
mainURL = "https://zerodemy.com/"
siteURL = "https://books.zerodemy.com/"
siteName = "জিরোডেমি বই"
siteNames = [ "জিরোডেমি বই", "ZeroBooks", "0dmey Books" ]
siteLang = "bn-BD"
siteLogo = "https://zerodemy.com/dist/img/logo%20temporary.png"



[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
home = [ "HTML", "RSS", "JSON"]